spring.application.name=BilUdlejning

# Thymeleaf Template Configuration
spring.thymeleaf.prefix=classpath:/Templates/
spring.thymeleaf.suffix=.html

# Database Configuration (set via environment variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
